[2022-05-11 07:02:19,428] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.staging manual__2022-05-11T07:02:18.222988+00:00 [queued]>
[2022-05-11 07:02:19,440] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.staging manual__2022-05-11T07:02:18.222988+00:00 [queued]>
[2022-05-11 07:02:19,440] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-11 07:02:19,440] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-11 07:02:19,440] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-11 07:02:19,453] {taskinstance.py:1264} INFO - Executing <Task(riotOperator): staging> on 2022-05-11 07:02:18.222988+00:00
[2022-05-11 07:02:19,460] {standard_task_runner.py:52} INFO - Started process 2202 to run task
[2022-05-11 07:02:19,464] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'staging', 'manual__2022-05-11T07:02:18.222988+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpc7gy24jy', '--error-file', '/tmp/tmpcz3iwbwd']
[2022-05-11 07:02:19,465] {standard_task_runner.py:77} INFO - Job 6: Subtask staging
[2022-05-11 07:02:19,517] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.staging manual__2022-05-11T07:02:18.222988+00:00 [running]> on host c411fdaf6506
[2022-05-11 07:02:19,566] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=staging
AIRFLOW_CTX_EXECUTION_DATE=2022-05-11T07:02:18.222988+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-11T07:02:18.222988+00:00
[2022-05-11 07:02:19,566] {riot_operator.py:60} INFO - StageToAzureLake not implemented yet
[2022-05-11 07:02:19,577] {riot_operator.py:67} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f428ed98ca0>>
[2022-05-11 07:02:19,577] {riot_operator.py:68} INFO - Created Azure Connection
[2022-05-11 07:02:19,587] {riot_operator.py:71} INFO - Created Riot Connection
[2022-05-11 07:02:19,587] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_operator.py", line 61, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_operator.py", line 78, in upload_to_azureLake
    self.type,
AttributeError: 'riotOperator' object has no attribute 'type'
[2022-05-11 07:02:19,598] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=staging, execution_date=20220511T070218, start_date=20220511T070219, end_date=20220511T070219
[2022-05-11 07:02:19,611] {standard_task_runner.py:89} ERROR - Failed to execute job 6 for task staging
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_operator.py", line 61, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_operator.py", line 78, in upload_to_azureLake
    self.type,
AttributeError: 'riotOperator' object has no attribute 'type'
[2022-05-11 07:02:19,636] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-11 07:02:19,665] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
