[2022-05-19 06:03:22,750] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 06:03:22,761] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 06:03:22,762] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 06:03:22,762] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-19 06:03:22,762] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 06:03:22,776] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_runesreforged.staging_runesreforged> on 2022-03-31 21:00:00+00:00
[2022-05-19 06:03:22,781] {standard_task_runner.py:52} INFO - Started process 333 to run task
[2022-05-19 06:03:22,785] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_runesreforged.staging_runesreforged', 'scheduled__2022-03-31T21:00:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmp9vqvfso7', '--error-file', '/tmp/tmpy21qvh8y']
[2022-05-19 06:03:22,786] {standard_task_runner.py:77} INFO - Job 150: Subtask paths.path_runesreforged.staging_runesreforged
[2022-05-19 06:03:22,871] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [running]> on host ca9a242fab95
[2022-05-19 06:03:22,946] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_runesreforged.staging_runesreforged
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T21:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-31T21:00:00+00:00
[2022-05-19 06:03:22,946] {riot_datadragon_toADLS_Operator.py:53} INFO - StageToAzureLake not implemented yet
[2022-05-19 06:03:22,947] {riot_datadragon_toADLS_Operator.py:59} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f3338e4bee0>>
[2022-05-19 06:03:22,947] {riot_datadragon_toADLS_Operator.py:60} INFO - Created Azure Connections
[2022-05-19 06:03:22,947] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 69, in upload_to_azureLake
    response_data = riot_hook.get_runes_reforged(version=self.version)
NameError: name 'riot_hook' is not defined
[2022-05-19 06:03:22,964] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=paths.path_runesreforged.staging_runesreforged, execution_date=20220331T210000, start_date=20220519T060322, end_date=20220519T060322
[2022-05-19 06:03:22,983] {standard_task_runner.py:89} ERROR - Failed to execute job 150 for task paths.path_runesreforged.staging_runesreforged
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 69, in upload_to_azureLake
    response_data = riot_hook.get_runes_reforged(version=self.version)
NameError: name 'riot_hook' is not defined
[2022-05-19 06:03:22,998] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-19 06:12:36,846] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 06:12:36,872] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 06:12:36,872] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 06:12:36,872] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-19 06:12:36,873] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 06:12:36,897] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_runesreforged.staging_runesreforged> on 2022-03-31 21:00:00+00:00
[2022-05-19 06:12:36,906] {standard_task_runner.py:52} INFO - Started process 620 to run task
[2022-05-19 06:12:36,915] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_runesreforged.staging_runesreforged', 'scheduled__2022-03-31T21:00:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmp14ncwyb0', '--error-file', '/tmp/tmpwuaypjt1']
[2022-05-19 06:12:36,918] {standard_task_runner.py:77} INFO - Job 159: Subtask paths.path_runesreforged.staging_runesreforged
[2022-05-19 06:12:37,013] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [running]> on host ca9a242fab95
[2022-05-19 06:12:37,128] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_runesreforged.staging_runesreforged
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T21:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-31T21:00:00+00:00
[2022-05-19 06:12:37,129] {riot_datadragon_toADLS_Operator.py:53} INFO - StageToAzureLake not implemented yet
[2022-05-19 06:12:37,130] {riot_datadragon_toADLS_Operator.py:59} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f3331474a90>>
[2022-05-19 06:12:37,131] {riot_datadragon_toADLS_Operator.py:60} INFO - Created Azure Connections
[2022-05-19 06:12:37,132] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 69, in upload_to_azureLake
    response_data = riot_hook.get_runes_reforged(version=self.version)
NameError: name 'riot_hook' is not defined
[2022-05-19 06:12:37,168] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=paths.path_runesreforged.staging_runesreforged, execution_date=20220331T210000, start_date=20220519T061236, end_date=20220519T061237
[2022-05-19 06:12:37,196] {standard_task_runner.py:89} ERROR - Failed to execute job 159 for task paths.path_runesreforged.staging_runesreforged
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 69, in upload_to_azureLake
    response_data = riot_hook.get_runes_reforged(version=self.version)
NameError: name 'riot_hook' is not defined
[2022-05-19 06:12:37,248] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-19 06:14:48,775] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 06:14:48,796] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 06:14:48,796] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 06:14:48,797] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-19 06:14:48,797] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 06:14:48,825] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_runesreforged.staging_runesreforged> on 2022-03-31 21:00:00+00:00
[2022-05-19 06:14:48,833] {standard_task_runner.py:52} INFO - Started process 697 to run task
[2022-05-19 06:14:48,840] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_runesreforged.staging_runesreforged', 'scheduled__2022-03-31T21:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmpp1xyxygk', '--error-file', '/tmp/tmp9obmcd0x']
[2022-05-19 06:14:48,842] {standard_task_runner.py:77} INFO - Job 161: Subtask paths.path_runesreforged.staging_runesreforged
[2022-05-19 06:14:48,940] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [running]> on host ca9a242fab95
[2022-05-19 06:14:49,042] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_runesreforged.staging_runesreforged
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T21:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-31T21:00:00+00:00
[2022-05-19 06:14:49,043] {riot_datadragon_toADLS_Operator.py:53} INFO - StageToAzureLake not implemented yet
[2022-05-19 06:14:49,043] {riot_datadragon_toADLS_Operator.py:59} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f3331474850>>
[2022-05-19 06:14:49,044] {riot_datadragon_toADLS_Operator.py:60} INFO - Created Azure Connections
[2022-05-19 06:14:49,045] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 69, in upload_to_azureLake
    response_data = self.riot_hook.get_runes_reforged(version=self.version)
TypeError: get_runes_reforged() got multiple values for argument 'version'
[2022-05-19 06:14:49,076] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=paths.path_runesreforged.staging_runesreforged, execution_date=20220331T210000, start_date=20220519T061448, end_date=20220519T061449
[2022-05-19 06:14:49,107] {standard_task_runner.py:89} ERROR - Failed to execute job 161 for task paths.path_runesreforged.staging_runesreforged
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 69, in upload_to_azureLake
    response_data = self.riot_hook.get_runes_reforged(version=self.version)
TypeError: get_runes_reforged() got multiple values for argument 'version'
[2022-05-19 06:14:49,134] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-19 07:31:38,790] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 07:31:38,802] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-19 07:31:38,802] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 07:31:38,802] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-19 07:31:38,802] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 07:31:38,820] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_runesreforged.staging_runesreforged> on 2022-03-31 21:00:00+00:00
[2022-05-19 07:31:38,826] {standard_task_runner.py:52} INFO - Started process 1418 to run task
[2022-05-19 07:31:38,829] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_runesreforged.staging_runesreforged', 'scheduled__2022-03-31T21:00:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmpje82s8ve', '--error-file', '/tmp/tmpxtdv9mdx']
[2022-05-19 07:31:38,831] {standard_task_runner.py:77} INFO - Job 193: Subtask paths.path_runesreforged.staging_runesreforged
[2022-05-19 07:31:38,965] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [running]> on host ca9a242fab95
[2022-05-19 07:31:39,017] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_runesreforged.staging_runesreforged
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T21:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-31T21:00:00+00:00
[2022-05-19 07:31:39,018] {riot_datadragon_toADLS_Operator.py:53} INFO - StageToAzureLake not implemented yet
[2022-05-19 07:31:39,018] {riot_datadragon_toADLS_Operator.py:59} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f3333aedcd0>>
[2022-05-19 07:31:39,018] {riot_datadragon_toADLS_Operator.py:60} INFO - Created Azure Connections
[2022-05-19 07:31:39,018] {riot_datadragon_toADLS_Operator.py:69} INFO - 12.9.1
[2022-05-19 07:31:39,018] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 70, in upload_to_azureLake
    response_data = self.riot_hook.get_runes_reforged(version=self.version)
TypeError: get_runes_reforged() got multiple values for argument 'version'
[2022-05-19 07:31:39,028] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=paths.path_runesreforged.staging_runesreforged, execution_date=20220331T210000, start_date=20220519T073138, end_date=20220519T073139
[2022-05-19 07:31:39,042] {standard_task_runner.py:89} ERROR - Failed to execute job 193 for task paths.path_runesreforged.staging_runesreforged
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 70, in upload_to_azureLake
    response_data = self.riot_hook.get_runes_reforged(version=self.version)
TypeError: get_runes_reforged() got multiple values for argument 'version'
[2022-05-19 07:31:39,087] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-20 04:50:13,074] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-20 04:50:13,084] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [queued]>
[2022-05-20 04:50:13,084] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-20 04:50:13,084] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-20 04:50:13,085] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-20 04:50:13,096] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_runesreforged.staging_runesreforged> on 2022-03-31 21:00:00+00:00
[2022-05-20 04:50:13,101] {standard_task_runner.py:52} INFO - Started process 5158 to run task
[2022-05-20 04:50:13,105] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_runesreforged.staging_runesreforged', 'scheduled__2022-03-31T21:00:00+00:00', '--job-id', '667', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmptkqoeyto', '--error-file', '/tmp/tmpa_aklgcw']
[2022-05-20 04:50:13,106] {standard_task_runner.py:77} INFO - Job 667: Subtask paths.path_runesreforged.staging_runesreforged
[2022-05-20 04:50:13,155] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_runesreforged.staging_runesreforged scheduled__2022-03-31T21:00:00+00:00 [running]> on host ca9a242fab95
[2022-05-20 04:50:13,217] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_runesreforged.staging_runesreforged
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T21:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-31T21:00:00+00:00
[2022-05-20 04:50:13,218] {riot_datadragon_toADLS_Operator.py:55} INFO - StageToAzureLake not implemented yet
[2022-05-20 04:50:13,230] {riot_datadragon_toADLS_Operator.py:63} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f9c740d13d0>>
[2022-05-20 04:50:13,230] {riot_datadragon_toADLS_Operator.py:64} INFO - Created Azure Connections
[2022-05-20 04:50:13,365] {riot_datadragon_toADLS_Operator.py:86} INFO - About to load to Azure!
[2022-05-20 04:50:13,365] {riot_datadragon_toADLS_Operator.py:87} INFO - runesreforged
[2022-05-20 04:50:13,367] {_universal.py:472} INFO - Request URL: 'https://leagueoflegends.blob.core.windows.net/datadragon-runesreforged/2022/5/20/4.json'/nRequest method: 'PUT'/nRequest headers:/n    'x-ms-blob-type': 'REDACTED'/n    'Content-Length': '39147'/n    'If-None-Match': '*'/n    'x-ms-version': 'REDACTED'/n    'Content-Type': 'application/octet-stream'/n    'Accept': 'application/xml'/n    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.8.12 (Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'/n    'x-ms-date': 'REDACTED'/n    'x-ms-client-request-id': '55d72fda-d7f8-11ec-bcb9-0242ac140004'/n    'Authorization': 'REDACTED'/nA body is sent with the request
[2022-05-20 04:50:13,696] {_universal.py:503} INFO - Response status: 201/nResponse headers:/n    'Content-Length': '0'/n    'Content-MD5': 'REDACTED'/n    'Last-Modified': 'Fri, 20 May 2022 04:50:15 GMT'/n    'ETag': '"0x8DA3A1C3B2A6F53"'/n    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'/n    'x-ms-request-id': '6b98eee8-d01e-00a9-4a05-6c34c3000000'/n    'x-ms-client-request-id': '55d72fda-d7f8-11ec-bcb9-0242ac140004'/n    'x-ms-version': 'REDACTED'/n    'x-ms-content-crc64': 'REDACTED'/n    'x-ms-request-server-encrypted': 'REDACTED'/n    'Date': 'Fri, 20 May 2022 04:50:14 GMT'
[2022-05-20 04:50:13,698] {riot_datadragon_toADLS_Operator.py:57} INFO - Upload league of legends data to Azure!
[2022-05-20 04:50:13,707] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=league_of_legends_dag, task_id=paths.path_runesreforged.staging_runesreforged, execution_date=20220331T210000, start_date=20220520T045013, end_date=20220520T045013
[2022-05-20 04:50:13,760] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-20 04:50:13,794] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
