[2022-06-23 21:51:34,486] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.staging_match_data manual__2022-06-23T21:35:02.543628+00:00 [queued]>
[2022-06-23 21:51:34,495] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.staging_match_data manual__2022-06-23T21:35:02.543628+00:00 [queued]>
[2022-06-23 21:51:34,495] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-23 21:51:34,495] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-06-23 21:51:34,495] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-06-23 21:51:34,516] {taskinstance.py:1264} INFO - Executing <Task(riot_matchDetailsToADLSOperator): staging_match_data> on 2022-06-23 21:35:02.543628+00:00
[2022-06-23 21:51:34,521] {standard_task_runner.py:52} INFO - Started process 1425 to run task
[2022-06-23 21:51:34,524] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'match_details_dag', 'staging_match_data', 'manual__2022-06-23T21:35:02.543628+00:00', '--job-id', '302', '--raw', '--subdir', 'DAGS_FOLDER/matchData_dag.py', '--cfg-path', '/tmp/tmpeo432fz9', '--error-file', '/tmp/tmpw9w_qys0']
[2022-06-23 21:51:34,525] {standard_task_runner.py:77} INFO - Job 302: Subtask staging_match_data
[2022-06-23 21:51:34,568] {logging_mixin.py:109} INFO - Running <TaskInstance: match_details_dag.staging_match_data manual__2022-06-23T21:35:02.543628+00:00 [running]> on host ebe3cc7dbee2
[2022-06-23 21:51:34,619] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=match_details_dag
AIRFLOW_CTX_TASK_ID=staging_match_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-23T21:35:02.543628+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-23T21:35:02.543628+00:00
[2022-06-23 21:51:34,619] {riot_matchdetails_toADLS_Operator.py:63} INFO - StageToAzureLake not implemented yet
[2022-06-23 21:51:34,630] {riot_matchdetails_toADLS_Operator.py:72} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f9fd73c0880>>
[2022-06-23 21:51:34,630] {riot_matchdetails_toADLS_Operator.py:73} INFO - Created Azure Connection
[2022-06-23 21:51:34,638] {riot_matchdetails_toADLS_Operator.py:76} INFO - Created Riot Connection
[2022-06-23 21:51:34,997] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2022-06-23 21:51:34,997] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2022-06-23 21:51:34,997] {Limits.py:87} INFO - rate limit changed from 0/0s to 50/10s
[2022-06-23 21:51:34,998] {logging_mixin.py:109} INFO - [{'leagueId': 'c6dcc962-5d54-4bcf-9991-901dd6acda00', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 'iMs6aSEysMHkgvAP6EYTPxJD-Sl78glMkmhNkL5teeVlhCGU', 'summonerName': 'Harukon', 'leaguePoints': 100, 'wins': 24, 'losses': 18, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': True, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': '2f5e40b1-b909-41f0-9cbe-f281d6f40092', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 'G1cpogdjZNzbBGChEgUOH9OQFqoV9NJGAgdsWtNq7jZTJUPy', 'summonerName': 'SirDur', 'leaguePoints': 100, 'wins': 60, 'losses': 32, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 2, 'losses': 1, 'progress': 'WWLNN'}}, {'leagueId': '574a3728-ceef-4f09-b163-e2e4aafed8f7', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 'aF3YCmHsyYVDmlMx67rHoHYW01r4Ctx3Id2iZkJa61ewRHZ7', 'summonerName': 'Iron Four Life', 'leaguePoints': 100, 'wins': 25, 'losses': 23, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': True, 'miniSeries': {'target': 3, 'wins': 1, 'losses': 0, 'progress': 'WNNNN'}}, {'leagueId': '3507019c-5cc7-44d9-8166-e68f9005c49a', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': '25_GY0jE0SxR8Mphq4WPXeWLCsITiMfZkFxX0PE5HI2uwfmt', 'summonerName': 'Matrix Divinity', 'leaguePoints': 100, 'wins': 44, 'losses': 21, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': 'ed607623-f7a5-44af-a642-3c0635b7dd0c', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 'EjZhIVYtrVC4sUbA28970uwi9Fi-QNYCDeKwjBb8oIGCXnZm', 'summonerName': 'Mark Brnovich', 'leaguePoints': 100, 'wins': 20, 'losses': 24, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': '48dcac4a-66a6-4d86-b16b-ff35ae646524', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 't31xRPoLHcZqHt6bOXXLuH7ZAog4gdsVsRVWPrn471rAA83M', 'summonerName': 'Taquitoboi', 'leaguePoints': 100, 'wins': 24, 'losses': 33, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 1, 'losses': 1, 'progress': 'LWNNN'}}, {'leagueId': '54d9a544-5e7b-412d-a309-66815ad92913', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 'a8ukyIW2Wawx8OFYh6kvU6XbMX-7l6I8FjKPdOiibfHDklBj', 'summonerName': 'Offensive Ward', 'leaguePoints': 100, 'wins': 17, 'losses': 12, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 1, 'progress': 'LNNNN'}}, {'leagueId': 'bceb11be-188d-4f8c-8f9e-69597ebe92f0', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 'imeCd9cTctBH1-_nbynvVW7uFyCmBC7Aby2tmM2KDvqvhsAN', 'summonerName': 'DenBlaze', 'leaguePoints': 100, 'wins': 38, 'losses': 40, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': True, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}, {'leagueId': '9cc95895-54a8-496d-a4cd-ed25c42f9056', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': '3Si823od9hN3NUdmA2JLl8RRB-pcl-x8Zvb5hQiVTzs-s09G', 'summonerName': 'I just met you', 'leaguePoints': 100, 'wins': 131, 'losses': 89, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': False, 'miniSeries': {'target': 3, 'wins': 2, 'losses': 2, 'progress': 'WLWLN'}}, {'leagueId': '3accc5cf-56d6-49df-b518-b38258d41010', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'GOLD', 'rank': 'I', 'summonerId': 'fGXbh_w6vjIM6LrYiGWuLv7Scg9Nt0hPCIlp5Fk3xAAb567H', 'summonerName': 'Immora1', 'leaguePoints': 100, 'wins': 130, 'losses': 112, 'veteran': False, 'inactive': False, 'freshBlood': False, 'hotStreak': True, 'miniSeries': {'target': 3, 'wins': 0, 'losses': 0, 'progress': 'NNNNN'}}]
[2022-06-23 21:51:35,091] {Limits.py:87} INFO - rate limit changed from 0/0s to 2000/60s
[2022-06-23 21:51:35,402] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2022-06-23 21:51:35,402] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2022-06-23 21:51:35,403] {Limits.py:87} INFO - rate limit changed from 0/0s to 500/10s
[2022-06-23 21:51:35,611] {Limits.py:87} INFO - rate limit changed from 0/0s to 250/10s
[2022-06-23 21:52:05,133] {RateLimiterAdapter.py:41} INFO - waiting for 90.268816 seconds...
[2022-06-23 21:52:35,332] {local_task_job.py:211} WARNING - State of this instance has been externally set to None. Terminating instance.
[2022-06-23 21:52:35,334] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 1425. PIDs of all processes in the group: [1425]
[2022-06-23 21:52:35,335] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 1425
[2022-06-23 21:52:35,335] {taskinstance.py:1413} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-06-23 21:52:35,344] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 64, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 92, in upload_to_azureLake
    match = riot_hook.get_match_byid(self.region, match)
  File "/opt/airflow/plugins/custom_hooks/riot_hook.py", line 32, in get_match_byid
    match_details = self.lol_watcher.match.by_id(my_region, match_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/helpers.py", line 32, in remapper
    return api_call(*nargs, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/league_of_legends/MatchApiV5.py", line 32, in by_id
    return self._request_endpoint(
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/NamedEndpoint.py", line 36, in _request_endpoint
    return self._base_api.raw_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/BaseApi.py", line 30, in raw_request
    response = handler.preview_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/Handlers/RateLimiterAdapter.py", line 44, in preview_request
    time.sleep(to_wait.total_seconds())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1415, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-06-23 21:52:35,353] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=match_details_dag, task_id=staging_match_data, execution_date=20220623T213502, start_date=20220623T215134, end_date=20220623T215235
[2022-06-23 21:52:35,369] {standard_task_runner.py:89} ERROR - Failed to execute job 302 for task staging_match_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 64, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_matchdetails_toADLS_Operator.py", line 92, in upload_to_azureLake
    match = riot_hook.get_match_byid(self.region, match)
  File "/opt/airflow/plugins/custom_hooks/riot_hook.py", line 32, in get_match_byid
    match_details = self.lol_watcher.match.by_id(my_region, match_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/helpers.py", line 32, in remapper
    return api_call(*nargs, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/league_of_legends/MatchApiV5.py", line 32, in by_id
    return self._request_endpoint(
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/NamedEndpoint.py", line 36, in _request_endpoint
    return self._base_api.raw_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/_apis/BaseApi.py", line 30, in raw_request
    response = handler.preview_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/riotwatcher/Handlers/RateLimiterAdapter.py", line 44, in preview_request
    time.sleep(to_wait.total_seconds())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1415, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-06-23 21:52:35,387] {process_utils.py:70} INFO - Process psutil.Process(pid=1425, status='terminated', exitcode=1, started='21:51:34') (1425) terminated with exit code 1
