[2022-05-19 07:26:26,237] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_champions.staging_champions scheduled__2022-03-31T22:00:00+00:00 [queued]>
[2022-05-19 07:26:26,250] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_champions.staging_champions scheduled__2022-03-31T22:00:00+00:00 [queued]>
[2022-05-19 07:26:26,250] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 07:26:26,250] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-19 07:26:26,250] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 07:26:26,263] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_champions.staging_champions> on 2022-03-31 22:00:00+00:00
[2022-05-19 07:26:26,270] {standard_task_runner.py:52} INFO - Started process 1197 to run task
[2022-05-19 07:26:26,273] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_champions.staging_champions', 'scheduled__2022-03-31T22:00:00+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmpcp54n53s', '--error-file', '/tmp/tmp539cg9ub']
[2022-05-19 07:26:26,275] {standard_task_runner.py:77} INFO - Job 185: Subtask paths.path_champions.staging_champions
[2022-05-19 07:26:26,353] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_champions.staging_champions scheduled__2022-03-31T22:00:00+00:00 [running]> on host ca9a242fab95
[2022-05-19 07:26:26,435] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_champions.staging_champions
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T22:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-31T22:00:00+00:00
[2022-05-19 07:26:26,435] {riot_datadragon_toADLS_Operator.py:53} INFO - StageToAzureLake not implemented yet
[2022-05-19 07:26:26,436] {riot_datadragon_toADLS_Operator.py:59} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f3333b02160>>
[2022-05-19 07:26:26,436] {riot_datadragon_toADLS_Operator.py:60} INFO - Created Azure Connections
[2022-05-19 07:26:26,436] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 63, in upload_to_azureLake
    response_data = self.riot_hook.get_champions(version=self.version)
TypeError: get_champions() got multiple values for argument 'version'
[2022-05-19 07:26:26,451] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=paths.path_champions.staging_champions, execution_date=20220331T220000, start_date=20220519T072626, end_date=20220519T072626
[2022-05-19 07:26:26,471] {standard_task_runner.py:89} ERROR - Failed to execute job 185 for task paths.path_champions.staging_champions
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 63, in upload_to_azureLake
    response_data = self.riot_hook.get_champions(version=self.version)
TypeError: get_champions() got multiple values for argument 'version'
[2022-05-19 07:26:26,486] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-19 07:59:08,329] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_champions.staging_champions scheduled__2022-03-31T22:00:00+00:00 [queued]>
[2022-05-19 07:59:08,340] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_champions.staging_champions scheduled__2022-03-31T22:00:00+00:00 [queued]>
[2022-05-19 07:59:08,340] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 07:59:08,340] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-19 07:59:08,340] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-19 07:59:08,352] {taskinstance.py:1264} INFO - Executing <Task(riot_dataDragonToADLSOperator): paths.path_champions.staging_champions> on 2022-03-31 22:00:00+00:00
[2022-05-19 07:59:08,357] {standard_task_runner.py:52} INFO - Started process 385 to run task
[2022-05-19 07:59:08,361] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_champions.staging_champions', 'scheduled__2022-03-31T22:00:00+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmpl_tv4bx4', '--error-file', '/tmp/tmp6uq66vqz']
[2022-05-19 07:59:08,362] {standard_task_runner.py:77} INFO - Job 209: Subtask paths.path_champions.staging_champions
[2022-05-19 07:59:08,413] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_champions.staging_champions scheduled__2022-03-31T22:00:00+00:00 [running]> on host ca9a242fab95
[2022-05-19 07:59:08,461] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_champions.staging_champions
AIRFLOW_CTX_EXECUTION_DATE=2022-03-31T22:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-31T22:00:00+00:00
[2022-05-19 07:59:08,461] {riot_datadragon_toADLS_Operator.py:53} INFO - StageToAzureLake not implemented yet
[2022-05-19 07:59:08,462] {riot_datadragon_toADLS_Operator.py:59} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7fdd704a9940>>
[2022-05-19 07:59:08,462] {riot_datadragon_toADLS_Operator.py:60} INFO - Created Azure Connections
[2022-05-19 07:59:08,462] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 63, in upload_to_azureLake
    response_data = self.riot_hook.get_champions(version=self.version)
TypeError: get_champions() got multiple values for argument 'version'
[2022-05-19 07:59:08,476] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=paths.path_champions.staging_champions, execution_date=20220331T220000, start_date=20220519T075908, end_date=20220519T075908
[2022-05-19 07:59:08,493] {standard_task_runner.py:89} ERROR - Failed to execute job 209 for task paths.path_champions.staging_champions
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 54, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_datadragon_toADLS_Operator.py", line 63, in upload_to_azureLake
    response_data = self.riot_hook.get_champions(version=self.version)
TypeError: get_champions() got multiple values for argument 'version'
[2022-05-19 07:59:08,532] {local_task_job.py:154} INFO - Task exited with return code 1
